<?php

namespace EuroLiterie\structureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarqueRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepo extends EntityRepository
{
    public function getHtml()
    {
        return '<div class="marq admin-c border">
                    <input type="hidden" name="id" value="%idMarque%">
                    <section class="contentMarque">
                        <article class="adminMarque">
                            <label>Nom :</label><input type="text" name="nomMarque" value="%nomMarque%">
                            <label>Texte :</label><textarea class="textareaMarque" name="content" >%content%</textarea>
                            <label>Lien :</label><input type="text" name="marqueLien" value="%marqueLien%">
                        </article>
                        <article class="adminLogoMarque">
                            <label>Logo :</label><figure class="adminMarqueLogo"><img src="../../bundles/euroliteriestructure/images/marques/%pngUrl%"></img></figure>
                            <section class="btn-logo modif">
                                <li>Modifier</li>
                            </section>
                        </article>
                    </section>
                    <article class="btn-admin maj">
                        <li>Mettre à jour</li>
                    </article>
                    <article class="btn-admin sup">
                        <li>Supprimer</li>
                    </article>
                </div>';
    }

    public function getNew()
    {
        $marque = new Marque ();
        $em = $this->getEntityManager();
        $em->persist($marque);
        $em->flush();
        $sql = 'select p from EuroLiteriestructureBundle:Promotion p where p.id = (select max(m.id) from EuroLiteriestructureBundle:Promotion m)';
        return $em->createQuery($sql)->getSingleResult();
    }
}
